apiVersion: apps/v1
kind: Deployment
metadata:
  name: awkn-api-socialwall-user-deployment
  namespace: awkn-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awkn-socialwall-user-api
  template:
    metadata:
      labels:
        app: awkn-socialwall-user-api
    spec:
      containers:
        - name: awkn-socialwall-user-api
          image: awokenin.azurecr.io/awkn-socialwall-user-backend-dev:dev-v25
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: ARANGO_URL
              value: "https://chrome.awokenin.com"
            - name: ARANGO_USERNAME
              value: "root"
            - name: ARANGO_PASSWORD
              value: "rootpassword"
            - name: ARANGO_DATABASE_NAME
              value: "awokenin"
            - name: REDIRECT_URL
              value: "https://dev.awokenin.com/session-expired"
            - name: KEYCLOAK_PUBLIC_KEY
              valueFrom: 
                configMapKeyRef: 
                  name: keycloak-public-key-config
                  key: KEYCLOAK_PUBLIC_KEY
      imagePullSecrets:
        - name: acr-secret

---
# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: awkn-socialwall-user-api-service
  namespace: awkn-dev
spec:
  selector:
    app: awkn-socialwall-user-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
