apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: awkn-dev
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeserver
          image: awokenin.azurecr.io/awkn-backend:image.v4.5
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: AWKN_CONNECTION_STRING
              value: "DefaultEndpointsProtocol=https;AccountName=awknstorage;AccountKey=Hl4Z7DDa5+m5YjsVH9+EV03w8+P47U3zddOji0O1HPzoTCtKWfnS/uvJwtNPyS8D/FefyUGSBp5J+ASt0CxXaw==;EndpointSuffix=core.windows.net"
            - name: CONTAINER_NAME
              value: "awkn-image"
            - name: VIDEO_CONTAINER_NAME
              value: "awkn-video"
            - name: RESUME_CONTAINER_NAME
              value: "awkn-resume"
            - name: AWKN_STORAGE_ACCOUNT
              value: "awknstorage"
            - name: REDIRECT_URL
              value: "https://test.awokenin.com/session-expired"
            - name: KEYCLOAK_PUBLIC_KEY
              value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsIQLG2rqYyRpJqoW3Id5vbMhXGgijF6/kNSLj5W/YD3/Din8lWfXsTCdtTbtYPrl4rbVugO0CC2v/O/lNw3dpQh4nfsYu/f0qehSTbr9P5hYE0uh8t7bXExSZHJbAoO9OeXQAol8WSHePexpH/S+5ETJFJWcA3nZdilTm9CxxjUo6wRWbpefSj+XTsK9bylS6YPYCzb2AaabZmdcSekWf/a9S+6vMaqSgWkwODzUPuw96W4BWVQ9yBtA/XldxowDuO/Irs8Q1eHtfTrM2BJe1XZxrs07negKGZEP/3YcCExfSq4A7ON5htTMprz5JzolxepRGZKOI24QyHSofO7zXwIDAQAB"
      imagePullSecrets:
        - name: acr-secret

---
# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: awkn-dev
spec:
  selector:
    app: nodeapp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
