apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: awkn-dev
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeserver
          image: awokenin.azurecr.io/awkn-backend:image.v4.5
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: AWKN_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: awkn-dev-api-secrets
                  key: AWKN_CONNECTION_STRING
            - name: CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  name: awkn-dev-api-config
                  key: CONTAINER_NAME
            - name: VIDEO_CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  name: awkn-dev-api-config
                  key: VIDEO_CONTAINER_NAME
            - name: RESUME_CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  name: awkn-dev-api-config
                  key: RESUME_CONTAINER_NAME
            - name: AWKN_STORAGE_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: awkn-dev-api-config
                  key: AWKN_STORAGE_ACCOUNT
            - name: REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: awkn-dev-api-config
                  key: REDIRECT_URL
            - name: KEYCLOAK_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: awkn-dev-api-secrets
                  key: KEYCLOAK_PUBLIC_KEY
      imagePullSecrets:
        - name: acr-secret

---
# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: awkn-dev
spec:
  selector:
    app: nodeapp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
