apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: awkn-dev
spec:
  selector:
    app: nodeapp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
