apiVersion: apps/v1
kind: Deployment
metadata:
  name: awkn-ui-test
  namespace: awkn-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awkn-ui-test
  template:
    metadata:
      labels:
        app: awkn-ui-test
    spec:
      containers:
        - name: awkn-ui-test
          image: awokenin.azurecr.io/awokenin-ui-test:dev-v244
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BASE_URL
              value: "https://dev.api.buzzbreach.com"
            - name: NEXTAUTH_SECRET
              value: "af017d04a8083251abdebb81b1fbb498"
            - name: NEXTAUTH_URL
              value: "https://dev.buzzbreach.com"
            - name: KEYCLOAK_CLIENT_ID
              value: "awokenin-users"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "bqUyddLarkkp1cX57cgA3CBkAdZ85Che"
            - name: KEYCLOAK_ISSUER
              value: "https://oidc.buzzbreach.com/realms/awokenin-dev"
            - name: UPLOADS_BASE_URL
              value: "https://dev.api.buzzbreach.com"
            - name: NEXT_PUBLIC_RECAPTCHA_SITE_KEY
              value: "6LcVJgcqAAAAADp4vruJHl1TG1aCFH7q4LAlr-lW"
            - name: RECAPTCHA_SECRET_KEY
              value: "6LcVJgcqAAAAAAyaLHKhJmXidoTHF18YIQP0U81f"
            - name: NEXT_PUBLIC_KEYCLOAK_URL
              value: "https://oidc.buzzbreach.com"
            - name: NEXT_PUBLIC_KEYCLOAK_REALM
              value: "awokenin-dev"
            - name: NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
              value: "awokenin-users"
            - name: NEXT_PUBLIC_KEYCLOAK_REDIRECT_URI
              value: "https://dev.buzzbreach.com/tea-buzz"
            - name: NEXT_PUBLIC_SOCKET_BASE_URL
              value: "https://dev.socket.buzzbreach.com"
          resources:
            limits:
              cpu: "1"
              memory: "2048Mi"
            requests:
              cpu: "0.5"
              memory: "1024Mi"
      imagePullSecrets:
        - name: acr-secret
