apiVersion: apps/v1
kind: Deployment
metadata:
  name: awkn-api-user-deployment
  namespace: awkn-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awkn-user-api
  template:
    metadata:
      labels:
        app: awkn-user-api
    spec:
      containers:
        - name: awkn-user-api
          image: awokenin.azurecr.io/awkn-user-backend:v2
          ports:
            - containerPort: 5020
          env:
            - name: PORT
              value: "5020"
            - name: ARANGO_URL
              value: "https://chrome.awokenin.com"
            - name: ARANGO_USERNAME
              value: "root"
            - name: ARANGO_PASSWORD
              value: "rootpassword"
            - name: ARANGO_DATABASE_NAME
              value: "awokenin"
      imagePullSecrets:
        - name: acr-secret
