apiVersion: apps/v1
kind: Deployment
metadata:
  name: awkn-api-corporate-page-deployment
  namespace: awkn-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awkn-corporate-page-api
  template:
    metadata:
      labels:
        app: awkn-corporate-page-api
    spec:
      containers:
        - name: awkn-corporate-page-api
          image: awokenin.azurecr.io/awkn-corporate-page-backend-dev:dev-v28
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: ARANGO_URL
              value: "https://chrome.awokenin.com"
            - name: ARANGO_USERNAME
              value: "root"
            - name: ARANGO_PASSWORD
              value: "rootpassword"
            - name: ARANGO_DATABASE_NAME
              value: "awokenin"
            - name: KEYCLOAK_CLIENT_ID
              value: "awokenin-blog"
            - name: KEYCLOAK_URL
              value: "https://keycloak.awokenin.com"
            - name: KEYCLOAK_ADMIN_CLIENT_ID
              value: "admin-cli"
            - name: KEYCLOAK_ADMIN_USERNAME
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "Password123"
            - name: KEYCLOAK_ADMIN_GRANT_TYPE
              value: "password"
            - name: REALM_NAME
              value: "awokenin"
            - name: EMAIL_HOST
              value: "smtp.gmail.com"
            - name: EMAIL_PORT
              value: "587"
            - name: EMAIL_HOST_USER
              value: "awokenin.s3b@gmail.com"
            - name: EMAIL_HOST_PASSWORD
              value: "wtdo anuk ueof batx"
            - name: BASE_URL
              value: "https://test.awokenin.com"
            - name: REDIRECT_URL
              value: "https://dev.awokenin.com/session-expired"
            - name: KEYCLOAK_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: keycloak-public-key-config
                  key: KEYCLOAK_PUBLIC_KEY
      imagePullSecrets:
        - name: acr-secret

---
# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: awkn-corporate-page-api-service
  namespace: awkn-dev
spec:
  selector:
    app: awkn-corporate-page-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
