apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awokenin-certificate
  namespace: istio-system
spec:
  secretName: awokenin-ca-tls
  commonName: awokenin.com
  isCA: false
  usages:
    - server auth
    - client auth
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  dnsNames:
    - awokenin.com
    - www.awokenin.com
    - api.awokenin.com
    - socket.awokenin.com
    - test.awokenin.com
    - test.api.awokenin.com
    - test.socket.awokenin.com
    - blogs.awokenin.com
    - oidc.awokenin.com
    - tools.awokenin.com
    - dev.awokenin.com
    - dev.api.awokenin.com
    - dev.socket.awokenin.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
