apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: awokenin-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "awokenin.com"
        - "www.awokenin.com"
        - "api.awokenin.com"
        - "socket.awokenin.com"
        - "test.awokenin.com"
        - "test.api.awokenin.com"
        - "test.socket.awokenin.com"
        - "blogs.awokenin.com"
        - "oidc.awokenin.com"
        - "tools.awokenin.com"
        - "dev.awokenin.com"
        - "dev.api.awokenin.com"
        - "dev.socket.awokenin.com"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: awokenin-ca-tls
      hosts:
        - "awokenin.com"
        - "www.awokenin.com"
        - "api.awokenin.com"
        - "socket.awokenin.com"
        - "test.awokenin.com"
        - "test.api.awokenin.com"
        - "test.socket.awokenin.com"
        - "blogs.awokenin.com"
        - "oidc.awokenin.com"
        - "tools.awokenin.com"
        - "dev.awokenin.com"
        - "dev.api.awokenin.com"
        - "dev.socket.awokenin.com"

