apiVersion: apps/v1
kind: Deployment
metadata:
  name: awkn-resume-parser-api
  namespace: awkn-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awkn-resume-parser-api
  template:
    metadata:
      labels:
        app: awkn-resume-parser-api
    spec:
      containers:
        - name: awkn-resume-parser-api
          image: awokenin.azurecr.io/awkn-resume-parser-api:v5
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: ARANGO_URL
              value: "https://chrome.awokenin.com"
            - name: ARANGO_USERNAME
              value: "root"
            - name: ARANGO_PASSWORD
              value: "rootpassword"
            - name: ARANGO_DATABASE_NAME
              value: "awokenin"
            - name: ARANGO_COLLECTION_NAME
              value: "resume-data"
            - name: KEYCLOAK_CLIENT_ID
              value: "awokenin-blog"
            - name: KEYCLOAK_URL
              value: "https://keycloak.awokenin.com"
            - name: KEYCLOAK_ADMIN_CLIENT_ID
              value: "admin-cli"
            - name: KEYCLOAK_ADMIN_USERNAME
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "Password123"
            - name: KEYCLOAK_ADMIN_GRANT_TYPE
              value: "password"
            - name: REALM_NAME
              value: "awokenin"
            - name: EMAIL_HOST
              value: "smtp.gmail.com"
            - name: EMAIL_PORT
              value: "587"
            - name: EMAIL_HOST_USER
              value: "awokenin.s3b@gmail.com"
            - name: EMAIL_HOST_PASSWORD
              value: "wtdo anuk ueof batx"
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
      imagePullSecrets:
        - name: acr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: awkn-resume-parser-api-service
  namespace: awkn-dev
spec:
  selector:
    app: awkn-resume-parser-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
