apiVersion: apps/v1
kind: Deployment
metadata:
  name: awkn-api-deployment
  namespace: awkn-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awkn-admin-api
  template:
    metadata:
      labels:
        app: awkn-admin-api
    spec:
      containers:
        - name: awkn-admin-api
          image: awokenin.azurecr.io/awkn-backend-admin-api:dev-v20
          ports:
            - containerPort: 5010
          env:
            - name: PORT
              value: "5010"
            - name: ARANGO_URL
              value: "https://chrome.awokenin.com"
            - name: ARANGO_USERNAME
              value: "root"
            - name: ARANGO_PASSWORD
              value: "rootpassword"
            - name: ARANGO_DATABASE_NAME
              value: "awokenin"
            - name: REDIRECT_URL
              value: "https://dev.awokenin.com/session-expired"
            - name: KEYCLOAK_CLIENT_ID
              value: "awokenin-users"
            - name: KEYCLOAK_URL
              value: "https://keycloak.awokenin.com"
            - name: KEYCLOAK_ADMIN_CLIENT_ID
              value: "admin-cli"
            - name: KEYCLOAK_ADMIN_USERNAME
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "Password123"
            - name: KEYCLOAK_ADMIN_GRANT_TYPE
              value: "password"
            - name: REALM_NAME
              value: "awokenin"
            - name: KEYCLOAK_PUBLIC_KEY
              valueFrom: 
                configMapKeyRef: 
                  name: keycloak-public-key-config
                  key: KEYCLOAK_PUBLIC_KEY
      imagePullSecrets:
        - name: acr-secret

---
# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: awkn-admin-api-service
  namespace: awkn-dev
spec:
  selector:
    app: awkn-admin-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5010
