apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-public-key-config
  namespace: awkn-dev
data:
  KEYCLOAK_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqm9iG9mkAOsE7DcQkwoTgLRlWjT+y4X1FXiM3XYLcllofAR4q8zLIJK6hzb0SRqRu+x0/8UjCriq72hiC+j+48Hwj2QIZlcfjyfQpeEECxfDHIgM7jjx39W0rrywqWyYm4fKJmxXWDFlNSIseFVc/XBSTB8pTqWhpjjVgcCFSqGBoNlcQEirYPvMAkoj63SKZgU60+/4zQSQi2yvuZwtp75X5pMIOqC3iF4XIbwWGivDLwx+kXLGddKwlpT/7+X7R0gIYQD3rf2jCdEamwY7+/ZO30OJFMBn/e94ybi/oYbST9M2Hi2+ojsTYBIIMkqr+KKQC+GeMHbo1Hw31vie8wIDAQAB
    -----END PUBLIC KEY-----
